In [2]:
import pandas as pd
df = pd.read_csv('Emotion_classify_Data.csv')
df.head()

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [3]:
df['Emotion'].value_counts()

Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64

In [5]:
df['output'] = df['Emotion'].map({'joy': 0, 'fear': 1, 'anger': 2})
df.head()

                                             Comment Emotion  output
0  i seriously hate one subject to death but now ...    fear       1
1                 im so full of life i feel appalled   anger       2
2  i sit here to write i start to dig out my feel...    fear       1
3  ive been really angry with r and i feel like a...     joy       0
4  i feel suspicious if there is no one outside l...    fear       1

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.Comment, 
    df.output, 
    test_size=0.2, # 20% samples will go to test dataset
    random_state=2022,
    stratify=df.output
)

In [7]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)

Shape of X_train:  (4749,)
Shape of X_test:  (1188,)