In [2]:
import pandas as pd
df = pd.read_csv('Emotion_classify_Data.csv')
df.head()

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [3]:
df['Emotion'].value_counts()

Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64

In [5]:
df['output'] = df['Emotion'].map({'joy': 0, 'fear': 1, 'anger': 2})
df.head()

                                             Comment Emotion  output
0  i seriously hate one subject to death but now ...    fear       1
1                 im so full of life i feel appalled   anger       2
2  i sit here to write i start to dig out my feel...    fear       1
3  ive been really angry with r and i feel like a...     joy       0
4  i feel suspicious if there is no one outside l...    fear       1

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.Comment, 
    df.output, 
    test_size=0.2, # 20% samples will go to test dataset
    random_state=2022,
    stratify=df.output
)

In [7]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)

Shape of X_train:  (4749,)
Shape of X_test:  (1188,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
clf = Pipeline([('vectorizer', CountVectorizer(ngram_range = (3, 3))), ('classifier', RandomForestClassifier())])

In [10]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer(ngram_range=(3, 3))),
                ('classifier', RandomForestClassifier())])

In [11]:
y_pred = clf.predict(X_test)

In [12]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.58      0.25      0.35       400
           1       0.37      0.79      0.50       388
           2       0.53      0.23      0.33       400

    accuracy                           0.42      1188
   macro avg       0.49      0.43      0.39      1188
weighted avg       0.49      0.42      0.39      1188

In [ ]:
clf = Pipeline([
    ('vectorizer_bi_grams', CountVectorizer(ngram_range = (1, 2))),                       #using the ngram_range parameter 
    ('random_forest', (RandomForestClassifier()))         
])
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.96      0.90       400
           1       0.95      0.88      0.92       388
           2       0.94      0.88      0.90       400

    accuracy                           0.91      1188
   macro avg       0.91      0.91      0.91      1188
weighted avg       0.91      0.91      0.91      1188

In [ ]:
clf = Pipeline([
    ('vectorizer_bi_grams', CountVectorizer()),                       #using the ngram_range parameter 
    ('random_forest', (RandomForestClassifier()))         
])
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))