<h2 align='center'>NLP Tutorial: Text Representation - Bag Of Words (BOW)</h2>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r""D:\gitrepo\nlp_practice\bag of words\spam.csv"")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
df.shape

(5572, 3)

In [ ]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

<h3>Train test split</h3>

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
type(X_train)

pandas.Series

In [ ]:
X_train[:4]

4255               How about clothes, jewelry, and trips?
5016    I think the other two still need to get cash b...
5441    By the way, make sure u get train to worc fore...
2363    How are you doing? Hope you've settled in for ...
Name: Message, dtype: str

In [ ]:
type(y_train)

pandas.Series

In [ ]:
y_train[:4]

4255    0
5016    0
5441    0
2363    0
Name: spam, dtype: int64

In [ ]:
type(X_train.values)

pandas.arrays.StringArray

<h3>Create bag of words representation using CountVectorizer</h3>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59146 stored elements and shape (4457, 7749)>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7749,))

In [ ]:
X_train_cv.shape

(4457, 7749)

In [ ]:
v.get_feature_names_out()[1771]

'chex'

In [ ]:
v.vocabulary_

{'how': 3526,
 'about': 764,
 'clothes': 1851,
 'jewelry': 3827,
 'and': 963,
 'trips': 7037,
 'think': 6844,
 'the': 6814,
 'other': 5016,
 'two': 7086,
 'still': 6477,
 'need': 4738,
 'to': 6931,
 'get': 3120,
 'cash': 1671,
 'but': 1570,
 'we': 7421,
 'can': 1625,
 'def': 2214,
 'be': 1269,
 'ready': 5607,
 'by': 1584,
 'way': 7416,
 'make': 4328,
 'sure': 6619,
 'train': 7006,
 'worc': 7599,
 'foregate': 2938,
 'street': 6506,
 'not': 4841,
 'shrub': 6134,
 'hill': 3438,
 'have': 3359,
 'fun': 3040,
 'night': 4787,
 'are': 1053,
 'you': 7716,
 'doing': 2390,
 'hope': 3494,
 've': 7261,
 'settled': 6038,
 'in': 3643,
 'for': 2936,
 'new': 4769,
 'school': 5943,
 'year': 7691,
 'just': 3881,
 'wishin': 7552,
 'gr8': 3214,
 'day': 2174,
 'no': 4805,
 'da': 2136,
 'today': 6937,
 'also': 928,
 'forgot': 2947,
 'jordan': 3858,
 'got': 3201,
 'voted': 7328,
 'out': 5027,
 'last': 4025,
 'nite': 4799,
 'good': 3184,
 'morning': 4599,
 'plz': 5277,
 'call': 1600,
 'me': 4416,
 'sir': 6182,
 'tension': 6767,
 'face': 2737,
 'smiling': 6253,
 'waste': 7397,
 'innocent': 3691,
 'terror': 6774,
 'cruel': 2080,
 'romantic': 5821,
 'lovable': 4228,
 'decent': 2195,
 'lt': 4253,
 'gt': 3260,
 'joker': 3849,
 'hot': 3512,
 'live': 4155,
 'fantasies': 2768,
 'now': 4856,
 '08707509020': 81,
 '20p': 350,
 'per': 5160,
 'min': 4491,
 'ntt': 4864,
 'ltd': 4254,
 'po': 5280,
 'box': 1451,
 '1327': 290,
 'croydon': 2077,
 'cr9': 2045,
 '5wb': 564,
 '0870': 67,
 'did': 2300,
 'that': 6810,
 'message': 4465,
 'hows': 3529,
 'pain': 5071,
 'dear': 2187,
 'don': 2400,
 'what': 7483,
 'use': 7216,
 'it': 3762,
 'ni8': 4778,
 'happy': 3340,
 'birthday': 1363,
 'with': 7557,
 'lots': 4218,
 'of': 4907,
 'love': 4229,
 'rakhesh': 5566,
 'nri': 4861,
 'sounds': 6336,
 'like': 4115,
 'there': 6829,
 'could': 2024,
 'lot': 4216,
 'time': 6900,
 'spent': 6376,
 'chastity': 1741,
 'device': 2279,
 'boy': 1468,
 'grins': 3245,
 'or': 4991,
 'take': 6685,
 'your': 7720,
 'beatings': 1274,
 'dog': 2381,
 'going': 3174,
 'lounge': 4225,
 'nice': 4780,
 'long': 4193,
 'bath': 1243,
 'text82228': 6785,
 'more': 4595,
 'ringtones': 5797,
 'logos': 4185,
 'games': 3069,
 'from': 3019,
 'www': 7655,
 'txt82228': 7091,
 'com': 1897,
 'questions': 5538,
 'info': 3678,
 'co': 1868,
 'uk': 7116,
 'regret': 5674,
 'cudnt': 2104,
 'pick': 5213,
 'drove': 2459,
 'down': 2424,
 'frm': 3009,
 'ctla': 2092,
 'at': 1115,
 'cochin': 1873,
 'home': 3481,
 'left': 4069,
 'mobile': 4556,
 'car': 1644,
 'ente': 2595,
 'style': 6540,
 'ishtamayoo': 3754,
 'bakrid': 1205,
 'chinatown': 1791,
 'porridge': 5327,
 'claypot': 1828,
 'rice': 5781,
 'yam': 7683,
 'cake': 1593,
 'fishhead': 2866,
 'beehoon': 1291,
 'either': 2546,
 'eat': 2509,
 'cheap': 1747,
 'den': 2238,
 'go': 3162,
 'cafe': 1591,
 'tok': 6943,
 'nydc': 4885,
 'somethin': 6301,
 'pls': 5270,
 'note': 4842,
 'all': 915,
 'she': 6072,
 'exposed': 2720,
 'find': 2846,
 'her': 3416,
 'if': 3602,
 'anyone': 1000,
 'else': 2557,
 'was': 7393,
 'vomiting': 7326,
 'is': 3751,
 'cat': 1678,
 'house': 3521,
 'let': 4088,
 'know': 3963,
 'later': 4031,
 'having': 3365,
 'lunch': 4263,
 'online': 4957,
 'why': 7512,
 'much': 4646,
 'would': 7623,
 'cost': 2015,
 'hire': 3446,
 'hitman': 3451,
 'project': 5456,
 'pa': 5060,
 'after': 854,
 'only': 4959,
 'come': 1902,
 'staff': 6426,
 'science': 5945,
 'nus': 4874,
 'edu': 2524,
 'sg': 6050,
 'phyhcmk': 5210,
 'teaching': 6733,
 'pc1323': 5144,
 'yup': 7736,
 'ok': 4929,
 'look': 4197,
 'timings': 6905,
 'then': 6825,
 'msg': 4629,
 'again': 859,
 'xuhui': 7667,
 'learn': 4059,
 'on': 4947,
 '2nd': 403,
 'may': 4407,
 'too': 6970,
 'lesson': 4086,
 '8am': 717,
 'bus': 1563,
 'send': 6011,
 'copy': 2004,
 'report': 5721,
 'this': 6851,
 'free': 2982,
 'welcome': 7458,
 'improved': 3641,
 'sex': 6043,
 'dogging': 2384,
 'club': 1854,
 'unsubscribe': 7175,
 'service': 6030,
 'reply': 5718,
 'stop': 6489,
 'msgs': 4635,
 '150p': 304,
 '18': 318,
 'my': 4676,
 'exam': 2683,
 'february': 2793,
 'wish': 7549,
 'great': 3235,
 'full': 3037,
 'name': 4698,
 'joke': 3848,
 'cos': 2013,
 'fees': 2802,
 'university': 7159,
 'florida': 2899,
 'seem': 5989,
 'actually': 813,
 'holla': 3477,
 'back': 1192,
 'diddy': 2301,
 'neighbor': 4750,
 'comes': 1904,
 'toothpaste': 6976,
 'every': 2656,
 'geeeee': 3102,
 'so': 6278,
 'barely': 1225,
 'stand': 6433,
 'll': 4163,
 'always': 932,
 'even': 2650,
 'its': 3770,
 'spirit': 6384,
 'bb': 1252,
 'soon': 6318,
 'trying': 7053,
 'well': 7460,
 'thats': 6813,
 'bad': 1195,
 'cant': 1636,
 'maid': 4319,
 'murderer': 4661,
 'coz': 2041,
 'man': 4338,
 'murdered': 4660,
 'th': 6797,
 'january': 3797,
 'as': 1084,
 'public': 5495,
 'holiday': 3476,
 'govt': 3210,
 'instituitions': 3706,
 'closed': 1846,
 'including': 3652,
 'post': 5343,
 'office': 4917,
 'understand': 7139,
 'right': 5786,
 'second': 5973,
 'gotta': 3206,
 'hit': 3449,
 'people': 5158,
 'up': 7180,
 'first': 2864,
 'hello': 3402,
 'peach': 5148,
 'tasts': 6710,
 'lush': 4264,
 'sent': 6019,
 'them': 6822,
 'do': 2369,
 'fighting': 2827,
 'world': 7609,
 'easy': 2508,
 'win': 7530,
 'lose': 4211,
 'bt': 1532,
 'fightng': 2828,
 'some1': 6294,
 'who': 7505,
 'close': 1845,
 'dificult': 2316,
 'yet': 7704,
 'hold': 3472,
 'him': 3441,
 'sorry': 6325,
 'went': 7466,
 'bed': 1286,
 'early': 2497,
 'nightnight': 4789,
 'dont': 2404,
 'pack': 5062,
 'buy': 1573,
 'any': 996,
 'store': 6496,
 'cereals': 1707,
 'must': 4668,
 'food': 2928,
 'gari': 3079,
 'something': 6302,
 '9ja': 742,
 'will': 7528,
 'miss': 4520,
 'recieve': 5640,
 'tone': 6959,
 'within': 7560,
 'next': 4776,
 '24hrs': 360,
 'terms': 6770,
 'conditions': 1950,
 'please': 5263,
 'see': 5984,
 'channel': 1724,
 'teletext': 6750,
 'pg': 5191,
 '750': 621,
 'winner': 7539,
 'mr': 4624,
 'foley': 2915,
 'won': 7585,
 'an': 958,
 'ipod': 3741,
 'exciting': 2689,
 'prizes': 5437,
 'keep': 3912,
 'eye': 2731,
 'ur': 7199,
 'visit': 7308,
 '82050': 656,
 'putting': 5520,
 'business': 1567,
 'put': 5518,
 'pictures': 5220,
 'ass': 1102,
 'facebook': 2738,
 'one': 4953,
 'most': 4604,
 'open': 4971,
 'ever': 2655,
 'met': 4472,
 'picture': 5219,
 'room': 5824,
 'hurt': 3563,
 'feel': 2796,
 'violated': 7298,
 'abt': 771,
 'making': 4332,
 'some': 6293,
 'pics': 5217,
 'bigger': 1345,
 'want': 7380,
 'virtual': 7305,
 'hug': 3544,
 'plans': 5251,
 'private': 5433,
 '2003': 346,
 'account': 792,
 'statement': 6450,
 'shows': 6130,
 '800': 639,
 'un': 7127,
 'redeemed': 5653,
 'points': 5302,
 '08718738002': 146,
 'identifier': 3596,
 'code': 1877,
 '48922': 510,
 'expires': 2714,
 '21': 351,
 '11': 265,
 '04': 13,
 'hey': 3426,
 'leave': 4063,
 'big': 1344,
 'deal': 2183,
 'care': 1649,
 'sickness': 6148,
 'thing': 6842,
 'round': 5831,
 'better': 1329,
 'lol': 4187,
 'chance': 1718,
 '250': 364,
 'wk': 7567,
 'txt': 7088,
 'action': 806,
 '80608': 649,
 'movietrivia': 4620,
 'tv': 7076,
 'custcare': 2119,
 '08712405022': 103,
 '1x150p': 342,
 'ill': 3612,
 'taxt': 6719,
 'massage': 4379,
 'tie': 6890,
 'pos': 5331,
 'argh': 1059,
 'lool': 4203,
 'ask': 1093,
 'around': 1072,
 'mids': 4481,
 'here': 3417,
 'lar': 4021,
 'wait': 7357,
 'lor': 4209,
 'stuff': 6534,
 'babe': 1184,
 'friend': 3003,
 'had': 3295,
 'cancel': 1629,
 'surprise': 6626,
 'reach': 5597,
 'minutes': 4510,
 'cool': 1999,
 'breeze': 1493,
 'bright': 1498,
 'sun': 6596,
 'fresh': 2996,
 'flower': 2901,
 'twittering': 7085,
 'birds': 1358,
 'these': 6831,
 'waiting': 7360,
 'goodmorning': 3189,
 'amp': 950,
 'yeh': 7694,
 'am': 934,
 'up4': 7181,
 'sat': 5912,
 'payed2day': 5137,
 'havbeen': 3358,
 'given': 3145,
 '50': 536,
 'pay': 5134,
 'rise': 5800,
 '4my': 524,
 'work': 7602,
 'havebeen': 3360,
 'made': 4305,
 'preschoolco': 5401,
 'ordinator': 5000,
 '2i': 391,
 'feelingood': 2799,
 'luv': 4265,
 'anything': 1005,
 'dinner': 2328,
 'camera': 1621,
 'phones': 5204,
 'linerental': 4130,
 '49': 511,
 'month': 4588,
 'cross': 2075,
 'ntwk': 4865,
 'mins': 4506,
 'price': 5419,
 'bundle': 1553,
 'deals': 2186,
 'avble': 1153,
 '08001950382': 48,
 'call2optout': 1602,
 'mf': 4474,
 'okay': 4930,
 'shining': 6086,
 'meant': 4423,
 'signing': 6157,
 'enjoyed': 2589,
 'content': 1979,
 'text': 6784,
 '61610': 575,
 'help': 3405,
 '08712400602450p': 96,
 'provided': 5481,
 'tones2you': 6962,
 'family': 2761,
 'bring': 1503,
 'happiness': 3339,
 'stability': 6425,
 'tranquility': 7012,
 'vibrant': 7277,
 'colourful': 1895,
 'life': 4104,
 'many': 4354,
 'seems': 5991,
 'special': 6360,
 'sight': 6152,
 'very': 7273,
 'few': 2813,
 'remain': 5686,
 'till': 6898,
 'maintain': 4325,
 'ends': 2579,
 'sh': 6051,
 'jas': 3801,
 'valued': 7246,
 'vodafone': 7318,
 'customer': 2121,
 'our': 5024,
 'computer': 1940,
 'has': 3349,
 'picked': 5214,
 '150': 302,
 'prize': 5436,
 'collect': 1887,
 '09061743386': 192,
 'attend': 1128,
 'driving': 2454,
 'times': 6901,
 'which': 7499,
 'give': 3144,
 'thanks': 6802,
 'when': 7490,
 're': 5596,
 'really': 5615,
 'able': 763,
 'friday': 3000,
 'alternative': 930,
 'yr': 7726,
 'term': 6768,
 'nobody': 4808,
 'decide': 2196,
 'where': 7494,
 'dad': 2139,
 'wants': 7384,
 'chinese': 1792,
 'wat': 7400,
 'decision': 2200,
 'pubs': 5497,
 'near': 4727,
 'frankie': 2973,
 'bennys': 1323,
 'warner': 7389,
 'cinema': 1814,
 'except': 2686,
 'theres': 6830,
 'chick': 1777,
 'huge': 3545,
 'boobs': 1421,
 'tantrum': 6704,
 'finished': 2854,
 'yeah': 7690,
 'point': 5301,
 'charge': 1730,
 'yes': 7701,
 'small': 6240,
 'kid': 3935,
 'boost': 1430,
 'secret': 5975,
 'energy': 2582,
 'nigh': 4786,
 'aha': 873,
 'objection': 4895,
 'bf': 1335,
 'coming': 1908,
 'egg': 2539,
 'watching': 7404,
 'telugu': 6757,
 'movie': 4618,
 'mode': 4567,
 'men': 4453,
 'pple': 5364,
 'marry': 4372,
 'their': 6820,
 'lovers': 4236,
 'becz': 1285,
 'they': 6837,
 'hav': 3356,
 'gud': 3266,
 'undrstndng': 7144,
 'dat': 2164,
 'avoids': 1161,
 'problems': 5443,
 'dis': 2339,
 'wil': 7524,
 'news': 4773,
 'person': 5178,
 'tomorrow': 6957,
 'best': 1324,
 'break': 1486,
 'chain': 1713,
 'suffer': 6574,
 'frnds': 3012,
 'whn': 7504,
 'read': 5603,
 'definitely': 2217,
 'module': 4569,
 'humanities': 3552,
 'sem': 6006,
 'izzit': 3780,
 'wan': 7375,
 'modules': 4570,
 '1st': 335,
 'shb': 6070,
 'thanx': 6807,
 'afternoon': 855,
 'job': 3837,
 'prospects': 5477,
 'missing': 4524,
 'being': 1308,
 'lazy': 4048,
 'bleak': 1379,
 'hmmm': 3460,
 'filled': 2836,
 'urgent': 7202,
 '09066612661': 231,
 'landline': 4009,
 'complimentary': 1934,
 'lux': 4268,
 'costa': 2016,
 'del': 2223,
 'sol': 6287,
 '1000': 252,
 'await': 1162,
 'collection': 1890,
 'ppm': 5365,
 'sae': 5876,
 'cs': 2084,
 'james': 3791,
 '28': 372,
 'eh74rr': 2543,
 'guy': 3283,
 'kadeem': 3890,
 'hasn': 3350,
 'been': 1292,
 'selling': 6004,
 'since': 6171,
 'he': 3370,
 'paranoid': 5095,
 'fuck': 3027,
 'doesn': 2379,
 'without': 7561,
 'til': 6897,
 'late': 4028,
 'tonight': 6965,
 'hi': 3430,
 'join': 3845,
 'sts': 6522,
 'meeting': 4435,
 'five': 2870,
 'class': 1826,
 'nokia': 4815,
 'phone': 5201,
 'lovly': 4241,
 'oz': 5059,
 'kinda': 3945,
 'flaky': 2878,
 'interested': 3712,
 'picking': 5215,
 'worth': 7618,
 'possible': 5341,
 'balls': 1209,
 'calls': 1615,
 'might': 4482,
 'ax': 1171,
 'im': 3616,
 'spending': 6375,
 'years': 7692,
 'brother': 1519,
 'his': 3447,
 'lets': 4089,
 'plan': 5245,
 'meet': 4433,
 'week': 7444,
 'spoiled': 6394,
 'wah': 7350,
 'wont': 7592,
 'us': 7212,
 'haha': 3298,
 'say': 5928,
 'oh': 4925,
 'god': 3167,
 'taken': 6687,
 'teeth': 6745,
 'paining': 5073,
 '07973788240': 41,
 '08715203649': 116,
 '40533': 481,
 '31': 435,
 '10': 250,
 'said': 5882,
 'purity': 5510,
 'friendship': 3005,
 'between': 1330,
 'reading': 5606,
 'forwarded': 2960,
 'seeing': 5986,
 'evng': 2671,
 'ryder': 5866,
 'unsold': 7172,
 'gibbs': 3129,
 'loan': 4170,
 'purpose': 5512,
 '500': 537,
 '75': 620,
 '000': 1,
 'homeowners': 3482,
 'tenants': 6763,
 'previously': 5417,
 'refused': 5666,
 '0800': 44,
 '1956669': 324,
 'receiving': 5634,
 'triple': 7036,
 'echo': 2515,
 'ringtone': 5795,
 'shortly': 6115,
 'enjoy': 2588,
 'liao': 4095,
 'doubt': 2422,
 'handle': 3318,
 'case': 1670,
 'handsome': 3321,
 'finding': 2847,
 'working': 7606,
 'towards': 6999,
 'getting': 3125,
 'net': 4756,
 'mummy': 4653,
 'boytoy': 1473,
 'does': 2378,
 'sister': 6185,
 'belongs': 1315,
 'pray': 5381,
 'fated': 2778,
 'shoranur': 6109,
 'incident': 3648,
 'hands': 3319,
 'together': 6941,
 'fuelled': 3034,
 'concern': 1945,
 'prior': 5430,
 'grief': 3244,
 'pass': 5113,
 'violence': 7299,
 'against': 860,
 'women': 7584,
 'top': 6977,
 'polyphonic': 5314,
 'tones': 6960,
 '087018728737': 75,
 'national': 4716,
 'rate': 5579,
 'toppoly': 6981,
 'tune': 7069,
 'subpoly': 6549,
 '81618': 655,
 'pole': 5306,
 'unsub': 7174,
 '08718727870': 142,
 '88800': 706,
 '89034': 710,
 'premium': 5395,
 'services': 6031,
 '08718711108': 133,
 'probably': 5440,
 'further': 3050,
 'replying': 5719,
 'mix': 4536,
 'html': 3538,
 'gbp4': 3095,
 'mfl': 4475,
 '1146': 269,
 'mk45': 4540,
 '2wt': 418,
 'course': 2034,
 'should': 6118,
 'stink': 6478,
 'loving': 4239,
 'rock': 5811,
 'addie': 820,
 'art': 1080,
 'swt': 6662,
 'thought': 6862,
 'nver': 4878,
 'tired': 6909,
 'little': 4154,
 'things': 6843,
 'persons': 5183,
 'somtimes': 6310,
 'those': 6859,
 'occupy': 4900,
 'biggest': 1346,
 'part': 5105,
 'hearts': 3387,
 'messages': 4467,
 'missed': 4522,
 'smile': 6249,
 'wonder': 7588,
 'crazy': 2056,
 'away': 1167,
 'sms': 6260,
 'ac': 776,
 'blind': 1385,
 'date': 2166,
 '4u': 531,
 'rodds1': 5814,
 'aberdeen': 758,
 'united': 7156,
 'kingdom': 3948,
 'check': 1752,
 'http': 3539,
 'img': 3623,
 'icmb3cktz8r7': 3589,
 'dates': 2168,
 'hide': 3432,
 'wif': 7518,
 'try': 7051,
 'scared': 5937,
 'dun': 2480,
 'mah': 4316,
 'loud': 4224,
 'puttin': 5519,
 'fone': 2924,
 'finish': 2852,
 'centre': 1704,
 'thank': 6801,
 'monday': 4579,
 'gals': 3065,
 'whatever': 7484,
 'excuse': 2690,
 'tampa': 6702,
 'before': 1298,
 'though': 6861,
 'gentleman': 3111,
 'treat': 7026,
 'dignity': 2320,
 'respect': 5743,
 'southern': 6342,
 'california': 1599,
 'darlin': 2158,
 'london': 4190,
 'smashed': 6244,
 'into': 3720,
 'another': 983,
 'driver': 2452,
 'dent': 2241,
 'xxx': 7671,
 'aight': 881,
 'bit': 1365,
 'tell': 6751,
 'congratulation': 1962,
 'playin': 5258,
 'space': 6347,
 'poker': 5303,
 'yo': 7711,
 'byatch': 1585,
 'whassup': 7482,
 'carlos': 1661,
 'taking': 6690,
 'sweet': 6648,
 'usual': 7225,
 'patty': 5131,
 'done': 2402,
 'smoke': 6255,
 'haul': 3354,
 'frnd': 3011,
 'avoid': 1159,
 'missunderstding': 4527,
 'wit': 7556,
 'beloved': 1317,
 'askd': 1094,
 'question': 5536,
 'hours': 3520,
 'answer': 986,
 'takes': 6688,
 'wrc': 7628,
 'rally': 5568,
 'lucozade': 4260,
 'le': 4053,
 '61200': 574,
 '25p': 367,
 'packs': 5065,
 'itcould': 3764,
 'sort': 6326,
 'upstairs': 7196,
 'hectic': 3393,
 'fell': 2804,
 'swoop': 6661,
 'hiya': 3453,
 'didn': 2302,
 'signal': 6154,
 'haven': 3361,
 'seen': 5992,
 'heard': 3382,
 'neither': 4752,
 'unusual': 7179,
 'itself': 3771,
 'hugs': 3548,
 'snogs': 6271,
 'becoz': 1284,
 'jan': 3793,
 'al': 896,
 'ofice': 4921,
 'cn': 1864,
 'fr': 2969,
 'duffer': 2476,
 'sis': 6184,
 'juz': 3886,
 'watched': 7402,
 'italian': 3763,
 'congratulations': 1963,
 'awarded': 1166,
 'cd': 1691,
 'vouchers': 7331,
 '125gift': 283,
 'guaranteed': 3264,
 'entry': 2604,
 '100': 251,
 'wkly': 7571,
 'draw': 2439,
 'music': 4665,
 '87066': 692,
 'tncs': 6930,
 'ldew': 4050,
 'com1win150ppmx3age16': 1898,
 'princess': 5426,
 'xmas': 7664,
 'offer': 4913,
 'latest': 4032,
 'motorola': 4611,
 'sonyericsson': 6316,
 'bluetooth': 1403,
 'dvd': 2490,
 'double': 2419,
 'orange': 4994,
 'mobileupd8': 4560,
 '08000839402': 45,
 '4qf2': 525,
 'todays': 6938,
 'numbers': 4870,
 'ending': 2577,
 '4882': 509,
 'selected': 5997,
 'receive': 5631,
 '350': 446,
 'award': 1165,
 'number': 4869,
 'matches': 4387,
 '09064019014': 210,
 'dare': 2153,
 'change': 1720,
 'ring': 5792,
 'already': 925,
 'bought': 1447,
 'eggs': 2540,
 'both': 1442,
 ...}

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7749,))

In [ ]:
np.where(X_train_np[0]!=0)

(array([ 764,  963, 1851, 3526, 3827, 7037]),)

In [ ]:
X_train[:4]

4255               How about clothes, jewelry, and trips?
5016    I think the other two still need to get cash b...
5441    By the way, make sure u get train to worc fore...
2363    How are you doing? Hope you've settled in for ...
Name: Message, dtype: str

In [ ]:
X_train_np[0][1771]

np.int64(0)

<h3>Train the naive bayes model</h3>

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

<h3>Evaluate Performance</h3>

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       963
           1       0.97      0.91      0.94       152

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

<h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       963
           1       0.97      0.91      0.94       152

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115